### ISSUE TITLE
Every time I have 2 cells left the game freezes and I can't finish playing

### ISSUE THREAD

**Issue by mbrajk** [alexandercstephens/elm-minesweeper#1]
See title.
See video: https://goo.gl/photos/CY2S8XjNRavTMhaw7

**Comment by mbrajk** [comment]
This is very important, I still want to finish that game I was playing.

**Comment by alexandercstephens** [comment]
Now you can.

**Comment by mbrajk** [comment]
This is excellent news, thanks!
